'use strict'

module.exports = {
  USERNAME_IS_NOT_AVAILABLE: 'USERNAME_IS_NOT_AVAILABLE',
  WRONG_CREDENTIAL: 'WRONG_CREDENTIAL',
  WRONG_USER_ID: 'WRONG_USER_ID',
  WRONG_LOAD_ROLES: 'WRONG_LOAD_ROLES',
  WRONG_LOAD_GROUPS: 'WRONG_LOAD_GROUPS',
  WRONG_LOAD_USERS: 'WRONG_LOAD_USERS',
  WRONG_ACCESS: 'USER DOES NOT HAVE ACCESS TO THIS OPERATION',
  MESSAGE_RECEIVER_NOT_FOUND: 'MESSAGE RECEIVER NOT FOUND'
}
