'use strict'

module.exports = {
  USERNAME_IS_NOT_AVAILABLE: 'USERNAME_IS_NOT_AVAILABLE',
  WRONG_CREDENTIAL: 'WRONG_CREDENTIAL',
  WRONG_USER_ID: 'WRONG_USER_ID',
  WRONG_LOAD_ROLES: 'WRONG_LOAD_ROLES',
  WRONG_LOAD_GROUPS: 'WRONG_LOAD_GROUPS',
  WRONG_LOAD_USERS: 'WRONG_LOAD_USERS',
  WRONG_ACCESS: 'USER DOES NOT HAVE ACCESS TO THIS OPERATION',
  MESSAGE_RECEIVER_NOT_FOUND: 'MESSAGE_RECEIVER_NOT FOUND',
  CANNOT_DELETE_A_GROUP_WITH_EXISTING_USERS:
    'CANNOT DELETE A GROUP WITH EXISTING USERS',
  CANNOT_DELETE_A_ROLE_WITH_EXISTING_USERS:
    'CANNOT DELETE A ROLE WITH EXISTING USERS',
  CANNOT_DELETE_A_SERIES_WITH_EXISTING_VIDEOS:
    'CANNOT DELETE A SERIES WITH EXISTING VIDEOS',
  CANNOT_DELETE_A_SERIES_WITH_EXISTING_GROUPS:
    'CANNOT DELETE A SERIES WITH EXISTING GROUPS',
  WRONG_CONNECT_TO_GCS: 'WRONG_CONNECT_TO_GCS',
  MESSAGE_ALREADY_STARRED: 'MESSAGE_ALREADY_STARRED',
  STARRED_MESSAGE_NOT_FOUND: 'STARRED_MESSAGE_NOT_FOUND',
  WRONG_STATUS_VALUE: 'WRONG_STATUS_VALUE',
  WRONG_PRIVATE_VALUE: 'WRONG_PRIVATE_VALUE',
  WRONG_EMAIL_TYPE: 'WRONG_EMAIL_TYPE',
  RECOVERY_TOKEN_IS_NOT_VALID: 'RECOVERY_TOKEN_IS_NOT_VALID',
  NO_CATEGORY_LIST: 'NO_CATEGORY_LIST'
}
